import "./globals.css";
import { Baloo_Bhai_2, Saira_Stencil_One } from 'next/font/google';
import SessionWrapper from "@/components/SessionWrapper";
const balooBhai2 = Baloo_Bhai_2({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-baloo-bhai-2',
});

const sairaStencilOne = Saira_Stencil_One({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-saira-stencil-one',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${balooBhai2.variable} ${sairaStencilOne.variable} antialiased`}
      >
        <SessionWrapper>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
